# Generated by Django 5.2 on 2025-05-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('feedback_text', models.TextField()),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('GuestID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('CNIC', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('ConfirmPassword', models.CharField(max_length=100)),
                ('ContactNo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('occupancy', models.CharField(max_length=10)),
                ('room_status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('room_desc', models.CharField(max_length=100)),
                ('roomtype_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('room_image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('service_image', models.CharField(max_length=200)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='Cash', max_length=20)),
                ('billing_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.guest'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.roomtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(to='HomePage.service'),
        ),
        migrations.CreateModel(
            name='BookedService',
            fields=[
                ('booked_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_name', models.CharField(max_length=100)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.guest')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.service')),
            ],
        ),
    ]
